apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-contenedor
        image: wmfuertes/walter:lastest # Reemplaza "tu-imagen" con el nombre de tu imagen
        ports:
        - containerPort: 80
